"""Canonical schemas. Every dataset adapter, labeler, and feature job
emits/consumes these so the pipeline stays coherent across sources."""

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Label provenance
# ---------------------------------------------------------------------------


class LabelSource(str, Enum):
    """Where a label came from. Never overwrite `HUMAN_ORIGINAL`."""

    HUMAN_ORIGINAL = "human_original"
    DATASET_METADATA = "dataset_metadata"
    SYNTHETIC_VLM = "synthetic_vlm"
    SYNTHETIC_LLM = "synthetic_llm"
    DERIVED_BEHAVIORAL = "derived_behavioral"
    DERIVED_NEURAL = "derived_neural"
    TRIBE_PROJECTION = "tribe_projection"
    ENSEMBLE = "ensemble"


Granularity = Literal["dataset", "video", "segment", "frame"]


class LabelValue(BaseModel):
    """A single label measurement plus provenance.

    Storing raw + z + percentile + value_01 alongside `source` and
    `granularity` is what lets us mix datasets without silently
    treating video-level scores as segment-level truth.
    """

    value: float | None = Field(default=None, description="Canonical 0-1 score.")
    raw_value: float | str | None = Field(default=None, description="Original dataset value, unscaled.")
    z: float | None = Field(default=None, description="Z-score within source dataset.")
    percentile: float | None = Field(default=None, ge=0.0, le=1.0)
    confidence: float = Field(default=1.0, ge=0.0, le=1.0)
    source: LabelSource
    granularity: Granularity = "segment"


# ---------------------------------------------------------------------------
# Videos and segments
# ---------------------------------------------------------------------------

Domain = Literal[
    "ad", "movie", "everyday", "education", "short_form",
    "narrative", "commercial", "lecture", "podcast", "unknown",
]


class CanonicalVideo(BaseModel):
    """One row per source video. Dataset adapters emit these."""

    video_id: str
    source_dataset: str
    media_uri: str
    duration_s: float | None = None
    domain: Domain = "unknown"
    raw_labels: dict[str, float | str | None] = Field(default_factory=dict)
    metadata: dict[str, str | int | float | bool | None] = Field(default_factory=dict)


# Standard label keys — keep this list short and curated. Add via PR.
STANDARD_LABEL_KEYS: tuple[str, ...] = (
    "attention",
    "memorability",
    "short_term_memorability",
    "long_term_memorability",
    "brand_memorability",
    "engagement",
    "recall",
    "confusion",
    "emotional_intensity",
    "semantic_surprise",
    "narrative_progress",
    "social_salience",
    "audio_salience",
    "visual_salience",
    "isc_proxy",
)


class Segment(BaseModel):
    """A short window of one video. The unit of all downstream work."""

    sample_id: str = Field(description="Stable ID: '{source}_{video_id}_seg_{idx:04d}'")
    source_dataset: str
    video_id: str
    domain: Domain = "unknown"
    start_time: float = Field(ge=0.0)
    end_time: float = Field(ge=0.0)
    duration: float = Field(ge=0.0)
    media_path: str | None = None
    audio_path: str | None = None
    frames_path: str | None = None
    transcript: str | None = None
    captions: list[str] = Field(default_factory=list)
    labels: dict[str, LabelValue] = Field(default_factory=dict)
    split: Literal["train", "val", "test", "unassigned"] = "unassigned"

    @property
    def label_sources(self) -> dict[str, LabelSource]:
        return {k: v.source for k, v in self.labels.items()}


# ---------------------------------------------------------------------------
# Personas — synthetic viewer archetypes
# ---------------------------------------------------------------------------


class Persona(BaseModel):
    """A structured viewer archetype. Generate 5-50 of these first; only
    expand to 1000+ persona variants after the base pipeline works."""

    persona_id: str
    cluster: str = Field(description="Archetype family, e.g. 'fast_scroll' or 'cinematic_aesthetic'.")
    attention_weights: dict[str, float] = Field(
        default_factory=dict,
        description="Feature -> weight in [0, 1]. Keys: visual_composition, faces, dialogue, motion, novelty, product_clarity, humor, ...",
    )
    dislikes: dict[str, float] = Field(default_factory=dict)
    story: str = Field(default="", description="Short prose description for VLM prompting.")


class SyntheticLabel(BaseModel):
    """Per-segment label generated by a model (VLM, LLM, ensemble)."""

    segment_id: str
    persona_id: str | None = None
    scores: dict[str, float] = Field(default_factory=dict, description="Bounded to [0, 1].")
    reason: str = ""
    source: LabelSource = LabelSource.SYNTHETIC_VLM
    prompt_version: str = "v1"
    model_id: str | None = None


# ---------------------------------------------------------------------------
# Audience vectors — the research artifact
# ---------------------------------------------------------------------------


class AudienceVector(BaseModel):
    """A contrastive direction in some model's activation space.

    Computed as `mean(activations[high_set]) - mean(activations[low_set])`
    over segments scoring high/low on `target`. Score a new segment by
    projecting its activation onto `direction`.
    """

    vector_id: str
    target: str = Field(description="What this vector predicts, e.g. 'memorability' or 'fast_scroll_attention'.")
    model_id: str = Field(description="Source model, e.g. 'facebook/tribev2'.")
    layer: str = Field(description="Which layer/component the activations came from.")
    direction_uri: str = Field(description="Path to .safetensors/.npy holding the unit-norm direction.")
    dim: int
    positive_set_size: int
    negative_set_size: int
    notes: str = ""
